---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: istio-system
  description: Namespace istio-system.
  tags:
    - istio
    - kiali
    - core
    - servicemesh
  annotations:
    'backstage.io/kiali-namespace': istio-system
spec:
  type: service
  lifecycle: production
  owner: user:guest
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: bookinfo
  description: Bookinfo Application
  tags:
    - bookinfo
    - kiali
    - core
    - servicemesh
  annotations:
    'backstage.io/kiali-namespace': bookinfo
spec:
  type: service
  lifecycle: production
  owner: user:guest